modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT"
issueTrackerURL="https://github.com/DaDerpDuck/Seamless-Loading-Screen-Forge/issues"

[[mods]]
modId="seamless_loading_screen"
version="${file.jarVersion}"
displayName="Seamless Loading Screen"
displayURL="https://www.curseforge.com/minecraft/mc-mods/seamless-loading-screen-forge"
updateJSONURL="https://raw.githubusercontent.com/DaDerpDuck/Seamless-Loading-Screen-Forge/forge-1.16/update.json"
authors="Minenash, DaDerpDuck"
credits="Minenash, Forge Port: DaDerpDuck"
description='''
Forge port of Seamless Loading Screen
Takes a screenshot of the game when you leave a world or server, and displays it when you rejoin it
'''

[[dependencies.seamless_loading_screen]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.seamless_loading_screen]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_range}"
    ordering="NONE"
    side="CLIENT"